
package org.ow2.aspirerfid.commons.ale.wsdl.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T15:55:20.598+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "NoSuchNameException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class NoSuchNameExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.ale.wsdl.alelr.NoSuchNameException noSuchNameException;

    public NoSuchNameExceptionResponse() {
        super();
    }
    
    public NoSuchNameExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchNameExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchNameExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.alelr.NoSuchNameException noSuchNameException) {
        super(message);
        this.noSuchNameException = noSuchNameException;
    }

    public NoSuchNameExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.alelr.NoSuchNameException noSuchNameException, Throwable cause) {
        super(message, cause);
        this.noSuchNameException = noSuchNameException;
    }

    public org.ow2.aspirerfid.commons.ale.wsdl.alelr.NoSuchNameException getFaultInfo() {
        return this.noSuchNameException;
    }
}
