
package org.ow2.aspirerfid.commons.ale.wsdl.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Feb 08 19:02:25 EET 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "NonCompositeReaderException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class NonCompositeReaderExceptionResponse extends Exception {
    public static final long serialVersionUID = 20110208190225L;
    
    private org.ow2.aspirerfid.commons.ale.wsdl.alelr.NonCompositeReaderException nonCompositeReaderException;

    public NonCompositeReaderExceptionResponse() {
        super();
    }
    
    public NonCompositeReaderExceptionResponse(String message) {
        super(message);
    }
    
    public NonCompositeReaderExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NonCompositeReaderExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.alelr.NonCompositeReaderException nonCompositeReaderException) {
        super(message);
        this.nonCompositeReaderException = nonCompositeReaderException;
    }

    public NonCompositeReaderExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.alelr.NonCompositeReaderException nonCompositeReaderException, Throwable cause) {
        super(message, cause);
        this.nonCompositeReaderException = nonCompositeReaderException;
    }

    public org.ow2.aspirerfid.commons.ale.wsdl.alelr.NonCompositeReaderException getFaultInfo() {
        return this.nonCompositeReaderException;
    }
}
