//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.17 at 08:14:03 μμ EEST 
//


package org.ow2.aspirerfid.commons.apdl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.ow2.aspirerfid.commons.ale.model.ale.ECSpec;
import org.ow2.aspirerfid.commons.ale.model.alelr.LRSpec;
import org.ow2.aspirerfid.commons.epcis.model.EPCISMasterDataDocumentType;


/**
 * <p>Java class for DataField element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="DataField">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;element ref="{urn:epcglobal:ale:xsd:1}ECSpec"/>
 *           &lt;element ref="{urn:epcglobal:epcis-masterdata:xsd:1}EPCISMasterDataDocument"/>
 *           &lt;element ref="{urn:epcglobal:alelr:xsd:1}LRSpec"/>
 *         &lt;/choice>
 *         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *         &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ecSpec",
    "epcisMasterDataDocument",
    "lrSpec"
})
@XmlRootElement(name = "DataField")
public class ApdlDataField {

    @XmlElement(name = "ECSpec", namespace = "urn:epcglobal:ale:xsd:1")
    protected ECSpec ecSpec;
    @XmlElement(name = "EPCISMasterDataDocument", namespace = "urn:epcglobal:epcis-masterdata:xsd:1")
    protected EPCISMasterDataDocumentType epcisMasterDataDocument;
    @XmlElement(name = "LRSpec", namespace = "urn:epcglobal:alelr:xsd:1")
    protected LRSpec lrSpec;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the ecSpec property.
     * 
     * @return
     *     possible object is
     *     {@link ECSpec }
     *     
     */
    public ECSpec getECSpec() {
        return ecSpec;
    }

    /**
     * Sets the value of the ecSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECSpec }
     *     
     */
    public void setECSpec(ECSpec value) {
        this.ecSpec = value;
    }

    /**
     * Gets the value of the epcisMasterDataDocument property.
     * 
     * @return
     *     possible object is
     *     {@link EPCISMasterDataDocumentType }
     *     
     */
    public EPCISMasterDataDocumentType getEPCISMasterDataDocument() {
        return epcisMasterDataDocument;
    }

    /**
     * Sets the value of the epcisMasterDataDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPCISMasterDataDocumentType }
     *     
     */
    public void setEPCISMasterDataDocument(EPCISMasterDataDocumentType value) {
        this.epcisMasterDataDocument = value;
    }

    /**
     * Gets the value of the lrSpec property.
     * 
     * @return
     *     possible object is
     *     {@link LRSpec }
     *     
     */
    public LRSpec getLRSpec() {
        return lrSpec;
    }

    /**
     * Sets the value of the lrSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link LRSpec }
     *     
     */
    public void setLRSpec(LRSpec value) {
        this.lrSpec = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
