//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.23 at 04:33:28 μμ EEST 
//


package org.ow2.aspirerfid.commons.apdl.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ow2.aspirerfid.commons.apdl.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CLCBProc_QNAME = new QName("urn:ow2:aspirerfid:apdlspec:xsd:1", "CLCBProc");
    private final static QName _EBProc_QNAME = new QName("urn:ow2:aspirerfid:apdlspec:xsd:1", "EBProc");
    private final static QName _OLCBProc_QNAME = new QName("urn:ow2:aspirerfid:apdlspec:xsd:1", "OLCBProc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ow2.aspirerfid.commons.apdl.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OLCBProc }
     * 
     */
    public OLCBProc createOLCBProc() {
        return new OLCBProc();
    }

    /**
     * Create an instance of {@link EBProc }
     * 
     */
    public EBProc createEBProc() {
        return new EBProc();
    }

    /**
     * Create an instance of {@link CLCBProc }
     * 
     */
    public CLCBProc createCLCBProc() {
        return new CLCBProc();
    }

    /**
     * Create an instance of {@link ApdlDataField }
     * 
     */
    public ApdlDataField createApdlDataField() {
        return new ApdlDataField();
    }

    /**
     * Create an instance of {@link ApdlDataFields }
     * 
     */
    public ApdlDataFields createApdlDataFields() {
        return new ApdlDataFields();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CLCBProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", name = "CLCBProc")
    public JAXBElement<CLCBProc> createCLCBProc(CLCBProc value) {
        return new JAXBElement<CLCBProc>(_CLCBProc_QNAME, CLCBProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EBProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", name = "EBProc")
    public JAXBElement<EBProc> createEBProc(EBProc value) {
        return new JAXBElement<EBProc>(_EBProc_QNAME, EBProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OLCBProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", name = "OLCBProc")
    public JAXBElement<OLCBProc> createOLCBProc(OLCBProc value) {
        return new JAXBElement<OLCBProc>(_OLCBProc_QNAME, OLCBProc.class, null, value);
    }

}
