//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.17 at 08:14:03 μμ EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ow2.aspirerfid.commons.apdl.model;
