
package org.ow2.aspirerfid.programmableengine.ale.wsdl.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Nov 04 14:26:17 EET 2009
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "NoSuchNameException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class NoSuchNameExceptionResponse extends Exception {
    public static final long serialVersionUID = 20091104142617L;
    
    private org.ow2.aspirerfid.programmableengine.ale.wsdl.alelr.NoSuchNameException noSuchNameException;

    public NoSuchNameExceptionResponse() {
        super();
    }
    
    public NoSuchNameExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchNameExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchNameExceptionResponse(String message, org.ow2.aspirerfid.programmableengine.ale.wsdl.alelr.NoSuchNameException noSuchNameException) {
        super(message);
        this.noSuchNameException = noSuchNameException;
    }

    public NoSuchNameExceptionResponse(String message, org.ow2.aspirerfid.programmableengine.ale.wsdl.alelr.NoSuchNameException noSuchNameException, Throwable cause) {
        super(message, cause);
        this.noSuchNameException = noSuchNameException;
    }

    public org.ow2.aspirerfid.programmableengine.ale.wsdl.alelr.NoSuchNameException getFaultInfo() {
        return this.noSuchNameException;
    }
}
