
package org.ow2.aspirerfid.commons.ale.wsdl.ale;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T15:54:51.071+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ImplementationException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class ImplementationExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.ale.wsdl.ale.ImplementationException implementationException;

    public ImplementationExceptionResponse() {
        super();
    }
    
    public ImplementationExceptionResponse(String message) {
        super(message);
    }
    
    public ImplementationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImplementationExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.ale.ImplementationException implementationException) {
        super(message);
        this.implementationException = implementationException;
    }

    public ImplementationExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.ale.ImplementationException implementationException, Throwable cause) {
        super(message, cause);
        this.implementationException = implementationException;
    }

    public org.ow2.aspirerfid.commons.ale.wsdl.ale.ImplementationException getFaultInfo() {
        return this.implementationException;
    }
}
