
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T16:10:53.261+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "NoSuchSubscriptionException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class NoSuchSubscriptionExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.epcis.model.NoSuchSubscriptionException noSuchSubscriptionException;

    public NoSuchSubscriptionExceptionResponse() {
        super();
    }
    
    public NoSuchSubscriptionExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchSubscriptionExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSubscriptionExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.NoSuchSubscriptionException noSuchSubscriptionException) {
        super(message);
        this.noSuchSubscriptionException = noSuchSubscriptionException;
    }

    public NoSuchSubscriptionExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.NoSuchSubscriptionException noSuchSubscriptionException, Throwable cause) {
        super(message, cause);
        this.noSuchSubscriptionException = noSuchSubscriptionException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.NoSuchSubscriptionException getFaultInfo() {
        return this.noSuchSubscriptionException;
    }
}
