
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T16:10:53.270+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "QueryTooLargeException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class QueryTooLargeExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.epcis.model.QueryTooLargeException queryTooLargeException;

    public QueryTooLargeExceptionResponse() {
        super();
    }
    
    public QueryTooLargeExceptionResponse(String message) {
        super(message);
    }
    
    public QueryTooLargeExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryTooLargeExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.QueryTooLargeException queryTooLargeException) {
        super(message);
        this.queryTooLargeException = queryTooLargeException;
    }

    public QueryTooLargeExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.QueryTooLargeException queryTooLargeException, Throwable cause) {
        super(message, cause);
        this.queryTooLargeException = queryTooLargeException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.QueryTooLargeException getFaultInfo() {
        return this.queryTooLargeException;
    }
}
