
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T16:10:53.234+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "SecurityException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SecurityExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.epcis.model.SecurityException securityException;

    public SecurityExceptionResponse() {
        super();
    }
    
    public SecurityExceptionResponse(String message) {
        super(message);
    }
    
    public SecurityExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SecurityException securityException) {
        super(message);
        this.securityException = securityException;
    }

    public SecurityExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SecurityException securityException, Throwable cause) {
        super(message, cause);
        this.securityException = securityException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.SecurityException getFaultInfo() {
        return this.securityException;
    }
}
