
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:46:19 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "SubscribeNotPermittedException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SubscribeNotPermittedExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126184619L;
    
    private org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException;

    public SubscribeNotPermittedExceptionResponse() {
        super();
    }
    
    public SubscribeNotPermittedExceptionResponse(String message) {
        super(message);
    }
    
    public SubscribeNotPermittedExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscribeNotPermittedExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException) {
        super(message);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public SubscribeNotPermittedExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException, Throwable cause) {
        super(message, cause);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException getFaultInfo() {
        return this.subscribeNotPermittedException;
    }
}
