
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T16:10:53.307+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "SubscribeNotPermittedException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SubscribeNotPermittedExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException;

    public SubscribeNotPermittedExceptionResponse() {
        super();
    }
    
    public SubscribeNotPermittedExceptionResponse(String message) {
        super(message);
    }
    
    public SubscribeNotPermittedExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscribeNotPermittedExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException) {
        super(message);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public SubscribeNotPermittedExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException, Throwable cause) {
        super(message, cause);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.SubscribeNotPermittedException getFaultInfo() {
        return this.subscribeNotPermittedException;
    }
}
