
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-13T16:10:53.250+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ValidationException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class ValidationExceptionResponse extends Exception {
    
    private org.ow2.aspirerfid.commons.epcis.model.ValidationException validationException;

    public ValidationExceptionResponse() {
        super();
    }
    
    public ValidationExceptionResponse(String message) {
        super(message);
    }
    
    public ValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.ValidationException validationException, Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
