/*
 * Copyright (C) 2008-2010, Aspire
 * 
 * Aspire is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License version 2.1 as published by
 * the Free Software Foundation (the "LGPL").
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library in the file COPYING-LGPL-2.1; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied. See the GNU Lesser General Public License
 * for the specific language governing rights and limitations.
 */

package org.ow2.aspirerfid.commons.tracking.db;
// default package
// Generated 13 Σεπ 2010 8:25:25 μμ by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EpcClassProperties generated by hbm2java
 */
public class EpcClassProperties implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9036865021371392978L;
	private int id;
	private String properties;
	@SuppressWarnings("unchecked")
	private Set epcidForeignDatas = new HashSet(0);

	public EpcClassProperties() {
	}

	public EpcClassProperties(String properties) {
		this.properties = properties;
	}

	@SuppressWarnings("unchecked")
	public EpcClassProperties(String properties, Set epcidForeignDatas) {
		this.properties = properties;
		this.epcidForeignDatas = epcidForeignDatas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProperties() {
		return this.properties;
	}

	public void setProperties(String properties) {
		this.properties = properties;
	}

	@SuppressWarnings("unchecked")
	public Set getEpcidForeignDatas() {
		return this.epcidForeignDatas;
	}

	@SuppressWarnings("unchecked")
	public void setEpcidForeignDatas(Set epcidForeignDatas) {
		this.epcidForeignDatas = epcidForeignDatas;
	}
	
	@SuppressWarnings("unchecked")
	public void addEpcidForeignDatas(EpcidForeignData epcTag) {
		epcidForeignDatas.add(epcTag);
	}

}
