package org.ow2.aspirerfid.commons.tracking.db;
// default package
// Generated 13 Σεπ 2010 8:25:25 μμ by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EpcClassProperties generated by hbm2java
 */
public class EpcClassProperties implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9036865021371392978L;
	private int id;
	private String properties;
	@SuppressWarnings("unchecked")
	private Set epcidForeignDatas = new HashSet(0);

	public EpcClassProperties() {
	}

	public EpcClassProperties(String properties) {
		this.properties = properties;
	}

	@SuppressWarnings("unchecked")
	public EpcClassProperties(String properties, Set epcidForeignDatas) {
		this.properties = properties;
		this.epcidForeignDatas = epcidForeignDatas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProperties() {
		return this.properties;
	}

	public void setProperties(String properties) {
		this.properties = properties;
	}

	@SuppressWarnings("unchecked")
	public Set getEpcidForeignDatas() {
		return this.epcidForeignDatas;
	}

	@SuppressWarnings("unchecked")
	public void setEpcidForeignDatas(Set epcidForeignDatas) {
		this.epcidForeignDatas = epcidForeignDatas;
	}
	
	@SuppressWarnings("unchecked")
	public void addEpcidForeignDatas(EpcidForeignData epcTag) {
		epcidForeignDatas.add(epcTag);
	}

}
