package org.ow2.aspirerfid.commons.tracking.db;
// default package
// Generated 13 Σεπ 2010 8:25:25 μμ by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * EpcidForeignData generated by hbm2java
 */
public class EpcidForeignData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2152485547406237078L;
	private int id;
	private RemoteUri remoteUri;
	private EpcClassProperties epcClassProperties;
	private String tagId;
	private String latitude;
	private String longtiitude;
	private Date date;
	private String userData;

	public EpcidForeignData() {
	}

	public EpcidForeignData(RemoteUri remoteUri, String tagId, Date date) {
		this.remoteUri = remoteUri;
		this.tagId = tagId;
		this.date = date;
	}

	public EpcidForeignData(RemoteUri remoteUri,
			EpcClassProperties epcClassProperties, String tagId,
			String latitude, String longtiitude, Date date, String userData) {
		this.remoteUri = remoteUri;
		this.epcClassProperties = epcClassProperties;
		this.tagId = tagId;
		this.latitude = latitude;
		this.longtiitude = longtiitude;
		this.date = date;
		this.userData = userData;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public RemoteUri getRemoteUri() {
		return this.remoteUri;
	}

	public void setRemoteUri(RemoteUri remoteUri) {
		this.remoteUri = remoteUri;
	}

	public EpcClassProperties getEpcClassProperties() {
		return this.epcClassProperties;
	}

	public void setEpcClassProperties(EpcClassProperties epcClassProperties) {
		this.epcClassProperties = epcClassProperties;
	}

	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongtiitude() {
		return this.longtiitude;
	}

	public void setLongtiitude(String longtiitude) {
		this.longtiitude = longtiitude;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getUserData() {
		return this.userData;
	}

	public void setUserData(String userData) {
		this.userData = userData;
	}

}
