package org.ow2.aspirerfid.commons.tracking.db;
// default package
// Generated 13 Σεπ 2010 8:25:25 μμ by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * RemoteUri generated by hbm2java
 */
public class RemoteUri implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7455077015898974513L;
	private int id;
	private String uri;
	private String name;
	private String description;
	private String address;
	private String country;
	private String region;
	private String email;
	private String tel;
	private String fax;
	@SuppressWarnings("unchecked")
	private Set epcidForeignDatas = new HashSet(0);

	public RemoteUri() {
	}

	public RemoteUri(String uri) {
		this.uri = uri;
	}

	@SuppressWarnings("unchecked")
	public RemoteUri(String uri, String name, String description,
			String address, String country, String region, String email,
			String tel, String fax, Set epcidForeignDatas) {
		this.uri = uri;
		this.name = name;
		this.description = description;
		this.address = address;
		this.country = country;
		this.region = region;
		this.email = email;
		this.tel = tel;
		this.fax = fax;
		this.epcidForeignDatas = epcidForeignDatas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@SuppressWarnings("unchecked")
	public Set getEpcidForeignDatas() {
		return this.epcidForeignDatas;
	}

	@SuppressWarnings("unchecked")
	public void setEpcidForeignDatas(Set epcidForeignDatas) {
		this.epcidForeignDatas = epcidForeignDatas;
	}

	@SuppressWarnings("unchecked")
	public void addEpcidForeignDatas(EpcidForeignData epcTag) {
		epcidForeignDatas.add(epcTag);
	}

}
