package org.ow2.aspirerfid.commons.tracking.db;
// default package
// Generated 13 Σεπ 2010 8:25:25 μμ by Hibernate Tools 3.3.0.GA

/**
 * ReportedEpcid generated by hbm2java
 */
public class ReportedEpcid implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2028233414410719290L;
	private int id;
	private String tagId;
	private String latitude;
	private String longtitude;

	public ReportedEpcid() {
	}

	public ReportedEpcid(String tagId) {
		this.tagId = tagId;
	}

	public ReportedEpcid(String tagId, String latitude, String longtitude) {
		this.tagId = tagId;
		this.latitude = latitude;
		this.longtitude = longtitude;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(String longtitude) {
		this.longtitude = longtitude;
	}

}
