
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:46:19 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "QueryTooComplexException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class QueryTooComplexExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126184619L;
    
    private org.ow2.aspirerfid.commons.epcis.model.QueryTooComplexException queryTooComplexException;

    public QueryTooComplexExceptionResponse() {
        super();
    }
    
    public QueryTooComplexExceptionResponse(String message) {
        super(message);
    }
    
    public QueryTooComplexExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryTooComplexExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.QueryTooComplexException queryTooComplexException) {
        super(message);
        this.queryTooComplexException = queryTooComplexException;
    }

    public QueryTooComplexExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.QueryTooComplexException queryTooComplexException, Throwable cause) {
        super(message, cause);
        this.queryTooComplexException = queryTooComplexException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.QueryTooComplexException getFaultInfo() {
        return this.queryTooComplexException;
    }
}
