
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:46:19 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "QueryParameterException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class QueryParameterExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126184619L;
    
    private org.ow2.aspirerfid.commons.epcis.model.QueryParameterException queryParameterException;

    public QueryParameterExceptionResponse() {
        super();
    }
    
    public QueryParameterExceptionResponse(String message) {
        super(message);
    }
    
    public QueryParameterExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryParameterExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.QueryParameterException queryParameterException) {
        super(message);
        this.queryParameterException = queryParameterException;
    }

    public QueryParameterExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.QueryParameterException queryParameterException, Throwable cause) {
        super(message, cause);
        this.queryParameterException = queryParameterException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.QueryParameterException getFaultInfo() {
        return this.queryParameterException;
    }
}
