
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:46:19 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "SubscriptionControlsException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SubscriptionControlsExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126184619L;
    
    private org.ow2.aspirerfid.commons.epcis.model.SubscriptionControlsException subscriptionControlsException;

    public SubscriptionControlsExceptionResponse() {
        super();
    }
    
    public SubscriptionControlsExceptionResponse(String message) {
        super(message);
    }
    
    public SubscriptionControlsExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscriptionControlsExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SubscriptionControlsException subscriptionControlsException) {
        super(message);
        this.subscriptionControlsException = subscriptionControlsException;
    }

    public SubscriptionControlsExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.SubscriptionControlsException subscriptionControlsException, Throwable cause) {
        super(message, cause);
        this.subscriptionControlsException = subscriptionControlsException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.SubscriptionControlsException getFaultInfo() {
        return this.subscriptionControlsException;
    }
}
