
package org.ow2.aspirerfid.commons.epcis.wsdl.query;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:46:19 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "ValidationException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class ValidationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126184619L;
    
    private org.ow2.aspirerfid.commons.epcis.model.ValidationException validationException;

    public ValidationExceptionResponse() {
        super();
    }
    
    public ValidationExceptionResponse(String message) {
        super(message);
    }
    
    public ValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionResponse(String message, org.ow2.aspirerfid.commons.epcis.model.ValidationException validationException, Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public org.ow2.aspirerfid.commons.epcis.model.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
