package org.ow2.aspirerfid.ide.bpwme.diagram.xmleditor;

import org.eclipse.core.runtime.CoreException;
import org.ow2.aspirerfid.ide.bpwme.diagram.simpleditor.SimpleEditor;

/**
 * XML Editor generated by Eclipse.
 * 
 */
public class XMLEditor extends SimpleEditor {

	public static String ID = "bpwme.diagram.xmleditor.XMLEditor";
	private ColorManager colorManager;

	protected void internal_init() {
		configureInsertMode(SMART_INSERT, false);
		colorManager = new ColorManager();
		setSourceViewerConfiguration(new XMLConfiguration(colorManager));
		setDocumentProvider(new XMLDocumentProvider());
	}
	
	public void dispose() {
		colorManager.dispose();
		super.dispose();
	}
	
	
	public void refresh() {
		try {
			getDocumentProvider().resetDocument(getEditorInput());
		} catch (CoreException e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Auto refresh when every time get focus
	 */
	@Override
	public void setFocus() {
		refresh();
		super.setFocus();
	}
}
