package org.ow2.aspirerfid.ide.bpwme.diagram.xmleditor;

import org.eclipse.jface.text.rules.IWhitespaceDetector;

/**
 * XML Editor generated by Eclipse.
 * 
 */
public class XMLWhitespaceDetector implements IWhitespaceDetector {

	public boolean isWhitespace(char c) {
		return (c == ' ' || c == '\t' || c == '\n' || c == '\r');
	}
}
