
/*
 * 
 */

package org.ow2.aspirerfid.commons.ale.wsdl.alelr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:57:22 EET 2010
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "ALELRService", 
                  wsdlLocation = "file:EPCglobal-ale-1_1-alelr.wsdl",
                  targetNamespace = "urn:epcglobal:alelr:wsdl:1") 
public class ALELRService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:epcglobal:alelr:wsdl:1", "ALELRService");
    public final static QName ALELRServicePort = new QName("urn:epcglobal:alelr:wsdl:1", "ALELRServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:EPCglobal-ale-1_1-alelr.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:EPCglobal-ale-1_1-alelr.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ALELRService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ALELRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ALELRService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ALELRServicePortType
     */
    @WebEndpoint(name = "ALELRServicePort")
    public ALELRServicePortType getALELRServicePort() {
        return super.getPort(ALELRServicePort, ALELRServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ALELRServicePortType
     */
    @WebEndpoint(name = "ALELRServicePort")
    public ALELRServicePortType getALELRServicePort(WebServiceFeature... features) {
        return super.getPort(ALELRServicePort, ALELRServicePortType.class, features);
    }

}
