
package org.ow2.aspirerfid.commons.ale.wsdl.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:57:22 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "ImmutableReaderException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ImmutableReaderExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126185722L;
    
    private org.ow2.aspirerfid.commons.ale.wsdl.alelr.ImmutableReaderException immutableReaderException;

    public ImmutableReaderExceptionResponse() {
        super();
    }
    
    public ImmutableReaderExceptionResponse(String message) {
        super(message);
    }
    
    public ImmutableReaderExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImmutableReaderExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.alelr.ImmutableReaderException immutableReaderException) {
        super(message);
        this.immutableReaderException = immutableReaderException;
    }

    public ImmutableReaderExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.alelr.ImmutableReaderException immutableReaderException, Throwable cause) {
        super(message, cause);
        this.immutableReaderException = immutableReaderException;
    }

    public org.ow2.aspirerfid.commons.ale.wsdl.alelr.ImmutableReaderException getFaultInfo() {
        return this.immutableReaderException;
    }
}
