package org.ow2.aspirerfid.ide.bpwme.diagram.simpleditor;

import java.io.File;
import java.util.HashMap;

import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import org.eclipse.ui.IEditorInput;
import org.eclipse.ui.IEditorSite;
import org.eclipse.ui.IWorkbenchPage;
import org.eclipse.ui.PartInitException;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.texteditor.AbstractTextEditor;


/**
 * A simple text editor.
 * Generated by Eclipse.
 * 
 * @see org.eclipse.ui.examples.rcp.texteditor.editors.SimpleDocumentProvider
 * @since 3.0
 */
public class SimpleEditor extends AbstractTextEditor {

	public static String ID = "bpwme.diagram.simpleditor.SimpleEditor";
	protected static IEditorInput input = null;	
	
	public SimpleEditor() {
		super();
		// make sure we inherit all the text editing commands (delete line etc).
		setKeyBindingScopes(new String[] { "org.eclipse.ui.textEditorScope" });  //$NON-NLS-1$
		internal_init();
	}
	
	public static void setEditorInput(IEditorInput input) {
		SimpleEditor.input = input;
	}
	
	/**
	 * Initializes the document provider and source viewer configuration.
	 * Called by the constructor. Subclasses may replace this method.
	 */
	protected void internal_init() {
		configureInsertMode(SMART_INSERT, false);
		setDocumentProvider(new SimpleDocumentProvider());
	}
		
	public void refresh() {
		try {
			getDocumentProvider().resetDocument(getEditorInput());
		} catch (CoreException e) {
			e.printStackTrace();
		}
	}
}
