//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 03:47:52 μμ EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wfmc.org/2002/XPDL1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ow2.aspirerfid.commons.xpdl.model;
