//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.02 at 10:06:23 μμ EET 
//


package org.ow2.aspirerfid.programmableengine.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ow2.aspirerfid.programmableengine.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cost_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Cost");
    private final static QName _Length_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Length");
    private final static QName _Vendor_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Vendor");
    private final static QName _EPCISDocument_QNAME = new QName("urn:epcglobal:epcis:xsd:1", "EPCISDocument");
    private final static QName _StandardBusinessDocument_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocument");
    private final static QName _Icon_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Icon");
    private final static QName _Limit_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Limit");
    private final static QName _CLCBProc_QNAME = new QName("urn:ow2:aspirerfid:apdlspec:xsd:1", "CLCBProc");
    private final static QName _EBProc_QNAME = new QName("urn:ow2:aspirerfid:apdlspec:xsd:1", "EBProc");
    private final static QName _Description_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Description");
    private final static QName _Responsible_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Responsible");
    private final static QName _ActualParameter_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "ActualParameter");
    private final static QName _CostUnit_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "CostUnit");
    private final static QName _ScopeInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "ScopeInformation");
    private final static QName _CorrelationInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "CorrelationInformation");
    private final static QName _WaitingTime_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "WaitingTime");
    private final static QName _Priority_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Priority");
    private final static QName _InitialValue_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "InitialValue");
    private final static QName _EPCISMasterDataDocument_QNAME = new QName("urn:epcglobal:epcis-masterdata:xsd:1", "EPCISMasterDataDocument");
    private final static QName _Created_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Created");
    private final static QName _Duration_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Duration");
    private final static QName _LRSpec_QNAME = new QName("urn:epcglobal:alelr:xsd:1", "LRSpec");
    private final static QName _ValidTo_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "ValidTo");
    private final static QName _StandardBusinessDocumentHeader_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocumentHeader");
    private final static QName _WorkingTime_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "WorkingTime");
    private final static QName _Codepage_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Codepage");
    private final static QName _Version_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Version");
    private final static QName _ValidFrom_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "ValidFrom");
    private final static QName _Documentation_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Documentation");
    private final static QName _XPDLVersion_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "XPDLVersion");
    private final static QName _OLCBProc_QNAME = new QName("urn:ow2:aspirerfid:apdlspec:xsd:1", "OLCBProc");
    private final static QName _Countrykey_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Countrykey");
    private final static QName _ECSpec_QNAME = new QName("urn:epcglobal:ale:xsd:1", "ECSpec");
    private final static QName _Performer_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Performer");
    private final static QName _Author_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "Author");
    private final static QName _BusinessService_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "BusinessService");
    private final static QName _PriorityUnit_QNAME = new QName("http://www.wfmc.org/2002/XPDL1.0", "PriorityUnit");
    private final static QName _ECReports_QNAME = new QName("urn:epcglobal:ale:xsd:1", "ECReports");
    private final static QName _LRProperty_QNAME = new QName("urn:epcglobal:alelr:xsd:1", "LRProperty");
    private final static QName _EventListTypeExtension_QNAME = new QName("", "extension");
    private final static QName _EventListTypeObjectEvent_QNAME = new QName("", "ObjectEvent");
    private final static QName _EventListTypeTransactionEvent_QNAME = new QName("", "TransactionEvent");
    private final static QName _EventListTypeQuantityEvent_QNAME = new QName("", "QuantityEvent");
    private final static QName _EventListTypeAggregationEvent_QNAME = new QName("", "AggregationEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ow2.aspirerfid.programmableengine.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ECBoundarySpecExtension.StopTriggerList }
     * 
     */
    public ECBoundarySpecExtension.StopTriggerList createECBoundarySpecExtensionStopTriggerList() {
        return new ECBoundarySpecExtension.StopTriggerList();
    }

    /**
     * Create an instance of {@link DocumentIdentification }
     * 
     */
    public DocumentIdentification createDocumentIdentification() {
        return new DocumentIdentification();
    }

    /**
     * Create an instance of {@link DataFields }
     * 
     */
    public DataFields createDataFields() {
        return new DataFields();
    }

    /**
     * Create an instance of {@link AggregationEventExtensionType }
     * 
     */
    public AggregationEventExtensionType createAggregationEventExtensionType() {
        return new AggregationEventExtensionType();
    }

    /**
     * Create an instance of {@link ECReportGroupListMemberExtension2 }
     * 
     */
    public ECReportGroupListMemberExtension2 createECReportGroupListMemberExtension2() {
        return new ECReportGroupListMemberExtension2();
    }

    /**
     * Create an instance of {@link EPCISDocumentType }
     * 
     */
    public EPCISDocumentType createEPCISDocumentType() {
        return new EPCISDocumentType();
    }

    /**
     * Create an instance of {@link ActivitySets }
     * 
     */
    public ActivitySets createActivitySets() {
        return new ActivitySets();
    }

    /**
     * Create an instance of {@link EPCISBodyType }
     * 
     */
    public EPCISBodyType createEPCISBodyType() {
        return new EPCISBodyType();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link ECReportSpec }
     * 
     */
    public ECReportSpec createECReportSpec() {
        return new ECReportSpec();
    }

    /**
     * Create an instance of {@link ECBoundarySpecExtension2 }
     * 
     */
    public ECBoundarySpecExtension2 createECBoundarySpecExtension2() {
        return new ECBoundarySpecExtension2();
    }

    /**
     * Create an instance of {@link EnumerationValue }
     * 
     */
    public EnumerationValue createEnumerationValue() {
        return new EnumerationValue();
    }

    /**
     * Create an instance of {@link VocabularyElementExtensionType }
     * 
     */
    public VocabularyElementExtensionType createVocabularyElementExtensionType() {
        return new VocabularyElementExtensionType();
    }

    /**
     * Create an instance of {@link DataField }
     * 
     */
    public DataField createDataField() {
        return new DataField();
    }

    /**
     * Create an instance of {@link EPCISMasterDataHeaderExtensionType }
     * 
     */
    public EPCISMasterDataHeaderExtensionType createEPCISMasterDataHeaderExtensionType() {
        return new EPCISMasterDataHeaderExtensionType();
    }

    /**
     * Create an instance of {@link ParticipantType }
     * 
     */
    public ParticipantType createParticipantType() {
        return new ParticipantType();
    }

    /**
     * Create an instance of {@link ECReaderStat.Sightings }
     * 
     */
    public ECReaderStat.Sightings createECReaderStatSightings() {
        return new ECReaderStat.Sightings();
    }

    /**
     * Create an instance of {@link EPCISBodyExtensionType }
     * 
     */
    public EPCISBodyExtensionType createEPCISBodyExtensionType() {
        return new EPCISBodyExtensionType();
    }

    /**
     * Create an instance of {@link ECReportSpecExtension.StatProfileNames }
     * 
     */
    public ECReportSpecExtension.StatProfileNames createECReportSpecExtensionStatProfileNames() {
        return new ECReportSpecExtension.StatProfileNames();
    }

    /**
     * Create an instance of {@link TransitionRefs }
     * 
     */
    public TransitionRefs createTransitionRefs() {
        return new TransitionRefs();
    }

    /**
     * Create an instance of {@link VocabularyElementListType }
     * 
     */
    public VocabularyElementListType createVocabularyElementListType() {
        return new VocabularyElementListType();
    }

    /**
     * Create an instance of {@link LRProperty }
     * 
     */
    public LRProperty createLRProperty() {
        return new LRProperty();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link StandardBusinessDocumentHeader }
     * 
     */
    public StandardBusinessDocumentHeader createStandardBusinessDocumentHeader() {
        return new StandardBusinessDocumentHeader();
    }

    /**
     * Create an instance of {@link ECBoundarySpecExtension }
     * 
     */
    public ECBoundarySpecExtension createECBoundarySpecExtension() {
        return new ECBoundarySpecExtension();
    }

    /**
     * Create an instance of {@link ECTagStat.StatBlocks }
     * 
     */
    public ECTagStat.StatBlocks createECTagStatStatBlocks() {
        return new ECTagStat.StatBlocks();
    }

    /**
     * Create an instance of {@link BusinessLocationExtensionType }
     * 
     */
    public BusinessLocationExtensionType createBusinessLocationExtensionType() {
        return new BusinessLocationExtensionType();
    }

    /**
     * Create an instance of {@link LRSpec.Readers }
     * 
     */
    public LRSpec.Readers createLRSpecReaders() {
        return new LRSpec.Readers();
    }

    /**
     * Create an instance of {@link FormalParameters }
     * 
     */
    public FormalParameters createFormalParameters() {
        return new FormalParameters();
    }

    /**
     * Create an instance of {@link UnionType }
     * 
     */
    public UnionType createUnionType() {
        return new UnionType();
    }

    /**
     * Create an instance of {@link Participants }
     * 
     */
    public Participants createParticipants() {
        return new Participants();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link ECFilterListMemberExtension }
     * 
     */
    public ECFilterListMemberExtension createECFilterListMemberExtension() {
        return new ECFilterListMemberExtension();
    }

    /**
     * Create an instance of {@link StartMode }
     * 
     */
    public StartMode createStartMode() {
        return new StartMode();
    }

    /**
     * Create an instance of {@link EPCISHeaderExtensionType }
     * 
     */
    public EPCISHeaderExtensionType createEPCISHeaderExtensionType() {
        return new EPCISHeaderExtensionType();
    }

    /**
     * Create an instance of {@link ECSpec.LogicalReaders }
     * 
     */
    public ECSpec.LogicalReaders createECSpecLogicalReaders() {
        return new ECSpec.LogicalReaders();
    }

    /**
     * Create an instance of {@link Deadline }
     * 
     */
    public Deadline createDeadline() {
        return new Deadline();
    }

    /**
     * Create an instance of {@link TransitionRef }
     * 
     */
    public TransitionRef createTransitionRef() {
        return new TransitionRef();
    }

    /**
     * Create an instance of {@link ECReportGroupListMember }
     * 
     */
    public ECReportGroupListMember createECReportGroupListMember() {
        return new ECReportGroupListMember();
    }

    /**
     * Create an instance of {@link ECTagTimestampStat }
     * 
     */
    public ECTagTimestampStat createECTagTimestampStat() {
        return new ECTagTimestampStat();
    }

    /**
     * Create an instance of {@link ECReaderStat }
     * 
     */
    public ECReaderStat createECReaderStat() {
        return new ECReaderStat();
    }

    /**
     * Create an instance of {@link OLCBProc }
     * 
     */
    public OLCBProc createOLCBProc() {
        return new OLCBProc();
    }

    /**
     * Create an instance of {@link ECReports }
     * 
     */
    public ECReports createECReports() {
        return new ECReports();
    }

    /**
     * Create an instance of {@link ECSpec }
     * 
     */
    public ECSpec createECSpec() {
        return new ECSpec();
    }

    /**
     * Create an instance of {@link ApdlDataFields }
     * 
     */
    public ApdlDataFields createApdlDataFields() {
        return new ApdlDataFields();
    }

    /**
     * Create an instance of {@link EPCISDocumentExtensionType }
     * 
     */
    public EPCISDocumentExtensionType createEPCISDocumentExtensionType() {
        return new EPCISDocumentExtensionType();
    }

    /**
     * Create an instance of {@link ManifestItem }
     * 
     */
    public ManifestItem createManifestItem() {
        return new ManifestItem();
    }

    /**
     * Create an instance of {@link EPCISHeaderType }
     * 
     */
    public EPCISHeaderType createEPCISHeaderType() {
        return new EPCISHeaderType();
    }

    /**
     * Create an instance of {@link ECSpecExtension.PrimaryKeyFields }
     * 
     */
    public ECSpecExtension.PrimaryKeyFields createECSpecExtensionPrimaryKeyFields() {
        return new ECSpecExtension.PrimaryKeyFields();
    }

    /**
     * Create an instance of {@link Partner }
     * 
     */
    public Partner createPartner() {
        return new Partner();
    }

    /**
     * Create an instance of {@link ECReportGroupList }
     * 
     */
    public ECReportGroupList createECReportGroupList() {
        return new ECReportGroupList();
    }

    /**
     * Create an instance of {@link ECReportOutputFieldSpec }
     * 
     */
    public ECReportOutputFieldSpec createECReportOutputFieldSpec() {
        return new ECReportOutputFieldSpec();
    }

    /**
     * Create an instance of {@link ECSpec.ReportSpecs }
     * 
     */
    public ECSpec.ReportSpecs createECSpecReportSpecs() {
        return new ECSpec.ReportSpecs();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link EPCISMasterDataBodyExtensionType }
     * 
     */
    public EPCISMasterDataBodyExtensionType createEPCISMasterDataBodyExtensionType() {
        return new EPCISMasterDataBodyExtensionType();
    }

    /**
     * Create an instance of {@link LRSpecExtension }
     * 
     */
    public LRSpecExtension createLRSpecExtension() {
        return new LRSpecExtension();
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link VocabularyListType }
     * 
     */
    public VocabularyListType createVocabularyListType() {
        return new VocabularyListType();
    }

    /**
     * Create an instance of {@link ECFilterSpecExtension.FilterList }
     * 
     */
    public ECFilterSpecExtension.FilterList createECFilterSpecExtensionFilterList() {
        return new ECFilterSpecExtension.FilterList();
    }

    /**
     * Create an instance of {@link StandardBusinessDocument }
     * 
     */
    public StandardBusinessDocument createStandardBusinessDocument() {
        return new StandardBusinessDocument();
    }

    /**
     * Create an instance of {@link RedefinableHeader }
     * 
     */
    public RedefinableHeader createRedefinableHeader() {
        return new RedefinableHeader();
    }

    /**
     * Create an instance of {@link ECFilterSpecExtension }
     * 
     */
    public ECFilterSpecExtension createECFilterSpecExtension() {
        return new ECFilterSpecExtension();
    }

    /**
     * Create an instance of {@link ECReportOutputSpecExtension.FieldList }
     * 
     */
    public ECReportOutputSpecExtension.FieldList createECReportOutputSpecExtensionFieldList() {
        return new ECReportOutputSpecExtension.FieldList();
    }

    /**
     * Create an instance of {@link ECReportGroupExtension }
     * 
     */
    public ECReportGroupExtension createECReportGroupExtension() {
        return new ECReportGroupExtension();
    }

    /**
     * Create an instance of {@link ReadPointType }
     * 
     */
    public ReadPointType createReadPointType() {
        return new ReadPointType();
    }

    /**
     * Create an instance of {@link LRSpec.Properties }
     * 
     */
    public LRSpec.Properties createLRSpecProperties() {
        return new LRSpec.Properties();
    }

    /**
     * Create an instance of {@link BlockActivity }
     * 
     */
    public BlockActivity createBlockActivity() {
        return new BlockActivity();
    }

    /**
     * Create an instance of {@link ECReportGroup }
     * 
     */
    public ECReportGroup createECReportGroup() {
        return new ECReportGroup();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new Transition();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Transitions }
     * 
     */
    public Transitions createTransitions() {
        return new Transitions();
    }

    /**
     * Create an instance of {@link CorrelationInformation }
     * 
     */
    public CorrelationInformation createCorrelationInformation() {
        return new CorrelationInformation();
    }

    /**
     * Create an instance of {@link Split }
     * 
     */
    public Split createSplit() {
        return new Split();
    }

    /**
     * Create an instance of {@link AggregationEventType }
     * 
     */
    public AggregationEventType createAggregationEventType() {
        return new AggregationEventType();
    }

    /**
     * Create an instance of {@link ECBoundarySpec }
     * 
     */
    public ECBoundarySpec createECBoundarySpec() {
        return new ECBoundarySpec();
    }

    /**
     * Create an instance of {@link Tool }
     * 
     */
    public Tool createTool() {
        return new Tool();
    }

    /**
     * Create an instance of {@link ExternalReference }
     * 
     */
    public ExternalReference createExternalReference() {
        return new ExternalReference();
    }

    /**
     * Create an instance of {@link ECReportOutputSpecExtension2 }
     * 
     */
    public ECReportOutputSpecExtension2 createECReportOutputSpecExtension2() {
        return new ECReportOutputSpecExtension2();
    }

    /**
     * Create an instance of {@link ApdlDataField }
     * 
     */
    public ApdlDataField createApdlDataField() {
        return new ApdlDataField();
    }

    /**
     * Create an instance of {@link WorkflowProcesses }
     * 
     */
    public WorkflowProcesses createWorkflowProcesses() {
        return new WorkflowProcesses();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link ExtendedAttribute }
     * 
     */
    public ExtendedAttribute createExtendedAttribute() {
        return new ExtendedAttribute();
    }

    /**
     * Create an instance of {@link EPC }
     * 
     */
    public EPC createEPC() {
        return new EPC();
    }

    /**
     * Create an instance of {@link ECReportSpecExtension2 }
     * 
     */
    public ECReportSpecExtension2 createECReportSpecExtension2() {
        return new ECReportSpecExtension2();
    }

    /**
     * Create an instance of {@link ECReportOutputSpecExtension }
     * 
     */
    public ECReportOutputSpecExtension createECReportOutputSpecExtension() {
        return new ECReportOutputSpecExtension();
    }

    /**
     * Create an instance of {@link ECGroupSpecExtension }
     * 
     */
    public ECGroupSpecExtension createECGroupSpecExtension() {
        return new ECGroupSpecExtension();
    }

    /**
     * Create an instance of {@link ExtendedAttributes }
     * 
     */
    public ExtendedAttributes createExtendedAttributes() {
        return new ExtendedAttributes();
    }

    /**
     * Create an instance of {@link FinishMode }
     * 
     */
    public FinishMode createFinishMode() {
        return new FinishMode();
    }

    /**
     * Create an instance of {@link EPCListType }
     * 
     */
    public EPCListType createEPCListType() {
        return new EPCListType();
    }

    /**
     * Create an instance of {@link ECReports.Reports }
     * 
     */
    public ECReports.Reports createECReportsReports() {
        return new ECReports.Reports();
    }

    /**
     * Create an instance of {@link EPCISEventExtensionType }
     * 
     */
    public EPCISEventExtensionType createEPCISEventExtensionType() {
        return new EPCISEventExtensionType();
    }

    /**
     * Create an instance of {@link ECGroupSpec }
     * 
     */
    public ECGroupSpec createECGroupSpec() {
        return new ECGroupSpec();
    }

    /**
     * Create an instance of {@link ECFilterSpec.ExcludePatterns }
     * 
     */
    public ECFilterSpec.ExcludePatterns createECFilterSpecExcludePatterns() {
        return new ECFilterSpec.ExcludePatterns();
    }

    /**
     * Create an instance of {@link ECReportSpecExtension }
     * 
     */
    public ECReportSpecExtension createECReportSpecExtension() {
        return new ECReportSpecExtension();
    }

    /**
     * Create an instance of {@link ECFilterSpec.IncludePatterns }
     * 
     */
    public ECFilterSpec.IncludePatterns createECFilterSpecIncludePatterns() {
        return new ECFilterSpec.IncludePatterns();
    }

    /**
     * Create an instance of {@link Xpression }
     * 
     */
    public Xpression createXpression() {
        return new Xpression();
    }

    /**
     * Create an instance of {@link TransitionRestrictions }
     * 
     */
    public TransitionRestrictions createTransitionRestrictions() {
        return new TransitionRestrictions();
    }

    /**
     * Create an instance of {@link SchemaType }
     * 
     */
    public SchemaType createSchemaType() {
        return new SchemaType();
    }

    /**
     * Create an instance of {@link VocabularyExtensionType }
     * 
     */
    public VocabularyExtensionType createVocabularyExtensionType() {
        return new VocabularyExtensionType();
    }

    /**
     * Create an instance of {@link ECFilterSpec }
     * 
     */
    public ECFilterSpec createECFilterSpec() {
        return new ECFilterSpec();
    }

    /**
     * Create an instance of {@link Join }
     * 
     */
    public Join createJoin() {
        return new Join();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link ECGroupSpecExtension2 }
     * 
     */
    public ECGroupSpecExtension2 createECGroupSpecExtension2() {
        return new ECGroupSpecExtension2();
    }

    /**
     * Create an instance of {@link ObjectEventExtensionType }
     * 
     */
    public ObjectEventExtensionType createObjectEventExtensionType() {
        return new ObjectEventExtensionType();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     */
    public Applications createApplications() {
        return new Applications();
    }

    /**
     * Create an instance of {@link No }
     * 
     */
    public No createNo() {
        return new No();
    }

    /**
     * Create an instance of {@link BasicType }
     * 
     */
    public BasicType createBasicType() {
        return new BasicType();
    }

    /**
     * Create an instance of {@link EPCISMasterDataDocumentExtensionType }
     * 
     */
    public EPCISMasterDataDocumentExtensionType createEPCISMasterDataDocumentExtensionType() {
        return new EPCISMasterDataDocumentExtensionType();
    }

    /**
     * Create an instance of {@link BusinessScope }
     * 
     */
    public BusinessScope createBusinessScope() {
        return new BusinessScope();
    }

    /**
     * Create an instance of {@link ECSpecExtension2 }
     * 
     */
    public ECSpecExtension2 createECSpecExtension2() {
        return new ECSpecExtension2();
    }

    /**
     * Create an instance of {@link ECFilterListMember.PatList }
     * 
     */
    public ECFilterListMember.PatList createECFilterListMemberPatList() {
        return new ECFilterListMember.PatList();
    }

    /**
     * Create an instance of {@link ECReportGroupListExtension }
     * 
     */
    public ECReportGroupListExtension createECReportGroupListExtension() {
        return new ECReportGroupListExtension();
    }

    /**
     * Create an instance of {@link ECTagStat }
     * 
     */
    public ECTagStat createECTagStat() {
        return new ECTagStat();
    }

    /**
     * Create an instance of {@link FormalParameter }
     * 
     */
    public FormalParameter createFormalParameter() {
        return new FormalParameter();
    }

    /**
     * Create an instance of {@link ECFilterSpecExtension2 }
     * 
     */
    public ECFilterSpecExtension2 createECFilterSpecExtension2() {
        return new ECFilterSpecExtension2();
    }

    /**
     * Create an instance of {@link TransactionEventExtensionType }
     * 
     */
    public TransactionEventExtensionType createTransactionEventExtensionType() {
        return new TransactionEventExtensionType();
    }

    /**
     * Create an instance of {@link ECReportGroupCountExtension }
     * 
     */
    public ECReportGroupCountExtension createECReportGroupCountExtension() {
        return new ECReportGroupCountExtension();
    }

    /**
     * Create an instance of {@link WorkflowProcess }
     * 
     */
    public WorkflowProcess createWorkflowProcess() {
        return new WorkflowProcess();
    }

    /**
     * Create an instance of {@link Participant }
     * 
     */
    public Participant createParticipant() {
        return new Participant();
    }

    /**
     * Create an instance of {@link ProcessHeader }
     * 
     */
    public ProcessHeader createProcessHeader() {
        return new ProcessHeader();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Automatic }
     * 
     */
    public Automatic createAutomatic() {
        return new Automatic();
    }

    /**
     * Create an instance of {@link TimeEstimation }
     * 
     */
    public TimeEstimation createTimeEstimation() {
        return new TimeEstimation();
    }

    /**
     * Create an instance of {@link CLCBProc }
     * 
     */
    public CLCBProc createCLCBProc() {
        return new CLCBProc();
    }

    /**
     * Create an instance of {@link ECReportsExtension }
     * 
     */
    public ECReportsExtension createECReportsExtension() {
        return new ECReportsExtension();
    }

    /**
     * Create an instance of {@link VocabularyType }
     * 
     */
    public VocabularyType createVocabularyType() {
        return new VocabularyType();
    }

    /**
     * Create an instance of {@link QuantityEventType }
     * 
     */
    public QuantityEventType createQuantityEventType() {
        return new QuantityEventType();
    }

    /**
     * Create an instance of {@link ECReportSetSpec }
     * 
     */
    public ECReportSetSpec createECReportSetSpec() {
        return new ECReportSetSpec();
    }

    /**
     * Create an instance of {@link EPCISMasterDataDocumentType }
     * 
     */
    public EPCISMasterDataDocumentType createEPCISMasterDataDocumentType() {
        return new EPCISMasterDataDocumentType();
    }

    /**
     * Create an instance of {@link ECReportGroupCount }
     * 
     */
    public ECReportGroupCount createECReportGroupCount() {
        return new ECReportGroupCount();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link ECTime }
     * 
     */
    public ECTime createECTime() {
        return new ECTime();
    }

    /**
     * Create an instance of {@link EPCISMasterDataBodyType }
     * 
     */
    public EPCISMasterDataBodyType createEPCISMasterDataBodyType() {
        return new EPCISMasterDataBodyType();
    }

    /**
     * Create an instance of {@link ServiceTransaction }
     * 
     */
    public ServiceTransaction createServiceTransaction() {
        return new ServiceTransaction();
    }

    /**
     * Create an instance of {@link ECFilterListMember }
     * 
     */
    public ECFilterListMember createECFilterListMember() {
        return new ECFilterListMember();
    }

    /**
     * Create an instance of {@link ECReportGroupListMemberExtension.FieldList }
     * 
     */
    public ECReportGroupListMemberExtension.FieldList createECReportGroupListMemberExtensionFieldList() {
        return new ECReportGroupListMemberExtension.FieldList();
    }

    /**
     * Create an instance of {@link TransitionRestriction }
     * 
     */
    public TransitionRestriction createTransitionRestriction() {
        return new TransitionRestriction();
    }

    /**
     * Create an instance of {@link ActivitySet }
     * 
     */
    public ActivitySet createActivitySet() {
        return new ActivitySet();
    }

    /**
     * Create an instance of {@link TypeDeclaration }
     * 
     */
    public TypeDeclaration createTypeDeclaration() {
        return new TypeDeclaration();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link DeclaredType }
     * 
     */
    public DeclaredType createDeclaredType() {
        return new DeclaredType();
    }

    /**
     * Create an instance of {@link BusinessTransactionListType }
     * 
     */
    public BusinessTransactionListType createBusinessTransactionListType() {
        return new BusinessTransactionListType();
    }

    /**
     * Create an instance of {@link ReadPointExtensionType }
     * 
     */
    public ReadPointExtensionType createReadPointExtensionType() {
        return new ReadPointExtensionType();
    }

    /**
     * Create an instance of {@link SubFlow }
     * 
     */
    public SubFlow createSubFlow() {
        return new SubFlow();
    }

    /**
     * Create an instance of {@link ECReportMemberFieldExtension }
     * 
     */
    public ECReportMemberFieldExtension createECReportMemberFieldExtension() {
        return new ECReportMemberFieldExtension();
    }

    /**
     * Create an instance of {@link ECReportGroupListMemberExtension.Stats }
     * 
     */
    public ECReportGroupListMemberExtension.Stats createECReportGroupListMemberExtensionStats() {
        return new ECReportGroupListMemberExtension.Stats();
    }

    /**
     * Create an instance of {@link PackageHeader }
     * 
     */
    public PackageHeader createPackageHeader() {
        return new PackageHeader();
    }

    /**
     * Create an instance of {@link ECSightingStat }
     * 
     */
    public ECSightingStat createECSightingStat() {
        return new ECSightingStat();
    }

    /**
     * Create an instance of {@link ArrayType }
     * 
     */
    public ArrayType createArrayType() {
        return new ArrayType();
    }

    /**
     * Create an instance of {@link PartnerIdentification }
     * 
     */
    public PartnerIdentification createPartnerIdentification() {
        return new PartnerIdentification();
    }

    /**
     * Create an instance of {@link LRSpec }
     * 
     */
    public LRSpec createLRSpec() {
        return new LRSpec();
    }

    /**
     * Create an instance of {@link Manual }
     * 
     */
    public Manual createManual() {
        return new Manual();
    }

    /**
     * Create an instance of {@link EPCISEventListExtensionType }
     * 
     */
    public EPCISEventListExtensionType createEPCISEventListExtensionType() {
        return new EPCISEventListExtensionType();
    }

    /**
     * Create an instance of {@link TransactionEventType }
     * 
     */
    public TransactionEventType createTransactionEventType() {
        return new TransactionEventType();
    }

    /**
     * Create an instance of {@link ConformanceClass }
     * 
     */
    public ConformanceClass createConformanceClass() {
        return new ConformanceClass();
    }

    /**
     * Create an instance of {@link ObjectEventType }
     * 
     */
    public ObjectEventType createObjectEventType() {
        return new ObjectEventType();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link ECReportGroupListMemberExtension }
     * 
     */
    public ECReportGroupListMemberExtension createECReportGroupListMemberExtension() {
        return new ECReportGroupListMemberExtension();
    }

    /**
     * Create an instance of {@link ECReport }
     * 
     */
    public ECReport createECReport() {
        return new ECReport();
    }

    /**
     * Create an instance of {@link EBProc }
     * 
     */
    public EBProc createEBProc() {
        return new EBProc();
    }

    /**
     * Create an instance of {@link ExternalPackages }
     * 
     */
    public ExternalPackages createExternalPackages() {
        return new ExternalPackages();
    }

    /**
     * Create an instance of {@link ECBoundarySpecExtension.StartTriggerList }
     * 
     */
    public ECBoundarySpecExtension.StartTriggerList createECBoundarySpecExtensionStartTriggerList() {
        return new ECBoundarySpecExtension.StartTriggerList();
    }

    /**
     * Create an instance of {@link ECFieldSpec }
     * 
     */
    public ECFieldSpec createECFieldSpec() {
        return new ECFieldSpec();
    }

    /**
     * Create an instance of {@link ECReportExtension }
     * 
     */
    public ECReportExtension createECReportExtension() {
        return new ECReportExtension();
    }

    /**
     * Create an instance of {@link Implementation }
     * 
     */
    public Implementation createImplementation() {
        return new Implementation();
    }

    /**
     * Create an instance of {@link BusinessTransactionType }
     * 
     */
    public BusinessTransactionType createBusinessTransactionType() {
        return new BusinessTransactionType();
    }

    /**
     * Create an instance of {@link ECReportOutputFieldSpecExtension }
     * 
     */
    public ECReportOutputFieldSpecExtension createECReportOutputFieldSpecExtension() {
        return new ECReportOutputFieldSpecExtension();
    }

    /**
     * Create an instance of {@link QuantityEventExtensionType }
     * 
     */
    public QuantityEventExtensionType createQuantityEventExtensionType() {
        return new QuantityEventExtensionType();
    }

    /**
     * Create an instance of {@link ECFieldSpecExtension }
     * 
     */
    public ECFieldSpecExtension createECFieldSpecExtension() {
        return new ECFieldSpecExtension();
    }

    /**
     * Create an instance of {@link ECReportOutputSpec }
     * 
     */
    public ECReportOutputSpec createECReportOutputSpec() {
        return new ECReportOutputSpec();
    }

    /**
     * Create an instance of {@link TypeDeclarations }
     * 
     */
    public TypeDeclarations createTypeDeclarations() {
        return new TypeDeclarations();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link ECReportMemberField }
     * 
     */
    public ECReportMemberField createECReportMemberField() {
        return new ECReportMemberField();
    }

    /**
     * Create an instance of {@link VocabularyElementType }
     * 
     */
    public VocabularyElementType createVocabularyElementType() {
        return new VocabularyElementType();
    }

    /**
     * Create an instance of {@link SimulationInformation }
     * 
     */
    public SimulationInformation createSimulationInformation() {
        return new SimulationInformation();
    }

    /**
     * Create an instance of {@link ECSpecExtension }
     * 
     */
    public ECSpecExtension createECSpecExtension() {
        return new ECSpecExtension();
    }

    /**
     * Create an instance of {@link IDListType }
     * 
     */
    public IDListType createIDListType() {
        return new IDListType();
    }

    /**
     * Create an instance of {@link ExternalPackage }
     * 
     */
    public ExternalPackage createExternalPackage() {
        return new ExternalPackage();
    }

    /**
     * Create an instance of {@link BusinessLocationType }
     * 
     */
    public BusinessLocationType createBusinessLocationType() {
        return new BusinessLocationType();
    }

    /**
     * Create an instance of {@link EventListType }
     * 
     */
    public EventListType createEventListType() {
        return new EventListType();
    }

    /**
     * Create an instance of {@link Scope }
     * 
     */
    public Scope createScope() {
        return new Scope();
    }

    /**
     * Create an instance of {@link Responsibles }
     * 
     */
    public Responsibles createResponsibles() {
        return new Responsibles();
    }

    /**
     * Create an instance of {@link ActualParameters }
     * 
     */
    public ActualParameters createActualParameters() {
        return new ActualParameters();
    }

    /**
     * Create an instance of {@link EnumerationType }
     * 
     */
    public EnumerationType createEnumerationType() {
        return new EnumerationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Cost")
    public JAXBElement<String> createCost(String value) {
        return new JAXBElement<String>(_Cost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Length")
    public JAXBElement<String> createLength(String value) {
        return new JAXBElement<String>(_Length_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Vendor")
    public JAXBElement<String> createVendor(String value) {
        return new JAXBElement<String>(_Vendor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:epcis:xsd:1", name = "EPCISDocument")
    public JAXBElement<EPCISDocumentType> createEPCISDocument(EPCISDocumentType value) {
        return new JAXBElement<EPCISDocumentType>(_EPCISDocument_QNAME, EPCISDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocument")
    public JAXBElement<StandardBusinessDocument> createStandardBusinessDocument(StandardBusinessDocument value) {
        return new JAXBElement<StandardBusinessDocument>(_StandardBusinessDocument_QNAME, StandardBusinessDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Icon")
    public JAXBElement<String> createIcon(String value) {
        return new JAXBElement<String>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Limit")
    public JAXBElement<String> createLimit(String value) {
        return new JAXBElement<String>(_Limit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CLCBProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", name = "CLCBProc")
    public JAXBElement<CLCBProc> createCLCBProc(CLCBProc value) {
        return new JAXBElement<CLCBProc>(_CLCBProc_QNAME, CLCBProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EBProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", name = "EBProc")
    public JAXBElement<EBProc> createEBProc(EBProc value) {
        return new JAXBElement<EBProc>(_EBProc_QNAME, EBProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Responsible")
    public JAXBElement<String> createResponsible(String value) {
        return new JAXBElement<String>(_Responsible_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "ActualParameter")
    public JAXBElement<String> createActualParameter(String value) {
        return new JAXBElement<String>(_ActualParameter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "CostUnit")
    public JAXBElement<String> createCostUnit(String value) {
        return new JAXBElement<String>(_CostUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "ScopeInformation")
    public JAXBElement<Object> createScopeInformation(Object value) {
        return new JAXBElement<Object>(_ScopeInformation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrelationInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "CorrelationInformation", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<CorrelationInformation> createCorrelationInformation(CorrelationInformation value) {
        return new JAXBElement<CorrelationInformation>(_CorrelationInformation_QNAME, CorrelationInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "WaitingTime")
    public JAXBElement<String> createWaitingTime(String value) {
        return new JAXBElement<String>(_WaitingTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Priority")
    public JAXBElement<String> createPriority(String value) {
        return new JAXBElement<String>(_Priority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "InitialValue")
    public JAXBElement<String> createInitialValue(String value) {
        return new JAXBElement<String>(_InitialValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISMasterDataDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:epcis-masterdata:xsd:1", name = "EPCISMasterDataDocument")
    public JAXBElement<EPCISMasterDataDocumentType> createEPCISMasterDataDocument(EPCISMasterDataDocumentType value) {
        return new JAXBElement<EPCISMasterDataDocumentType>(_EPCISMasterDataDocument_QNAME, EPCISMasterDataDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Created")
    public JAXBElement<String> createCreated(String value) {
        return new JAXBElement<String>(_Created_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Duration")
    public JAXBElement<String> createDuration(String value) {
        return new JAXBElement<String>(_Duration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LRSpec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:alelr:xsd:1", name = "LRSpec")
    public JAXBElement<LRSpec> createLRSpec(LRSpec value) {
        return new JAXBElement<LRSpec>(_LRSpec_QNAME, LRSpec.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "ValidTo")
    public JAXBElement<String> createValidTo(String value) {
        return new JAXBElement<String>(_ValidTo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocumentHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocumentHeader")
    public JAXBElement<StandardBusinessDocumentHeader> createStandardBusinessDocumentHeader(StandardBusinessDocumentHeader value) {
        return new JAXBElement<StandardBusinessDocumentHeader>(_StandardBusinessDocumentHeader_QNAME, StandardBusinessDocumentHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "WorkingTime")
    public JAXBElement<String> createWorkingTime(String value) {
        return new JAXBElement<String>(_WorkingTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Codepage")
    public JAXBElement<String> createCodepage(String value) {
        return new JAXBElement<String>(_Codepage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "ValidFrom")
    public JAXBElement<String> createValidFrom(String value) {
        return new JAXBElement<String>(_ValidFrom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Documentation")
    public JAXBElement<String> createDocumentation(String value) {
        return new JAXBElement<String>(_Documentation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "XPDLVersion")
    public JAXBElement<String> createXPDLVersion(String value) {
        return new JAXBElement<String>(_XPDLVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OLCBProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ow2:aspirerfid:apdlspec:xsd:1", name = "OLCBProc")
    public JAXBElement<OLCBProc> createOLCBProc(OLCBProc value) {
        return new JAXBElement<OLCBProc>(_OLCBProc_QNAME, OLCBProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Countrykey")
    public JAXBElement<String> createCountrykey(String value) {
        return new JAXBElement<String>(_Countrykey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ECSpec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:ale:xsd:1", name = "ECSpec")
    public JAXBElement<ECSpec> createECSpec(ECSpec value) {
        return new JAXBElement<ECSpec>(_ECSpec_QNAME, ECSpec.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Performer")
    public JAXBElement<String> createPerformer(String value) {
        return new JAXBElement<String>(_Performer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "Author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "BusinessService", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<BusinessService> createBusinessService(BusinessService value) {
        return new JAXBElement<BusinessService>(_BusinessService_QNAME, BusinessService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wfmc.org/2002/XPDL1.0", name = "PriorityUnit")
    public JAXBElement<String> createPriorityUnit(String value) {
        return new JAXBElement<String>(_PriorityUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ECReports }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:ale:xsd:1", name = "ECReports")
    public JAXBElement<ECReports> createECReports(ECReports value) {
        return new JAXBElement<ECReports>(_ECReports_QNAME, ECReports.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LRProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:epcglobal:alelr:xsd:1", name = "LRProperty")
    public JAXBElement<LRProperty> createLRProperty(LRProperty value) {
        return new JAXBElement<LRProperty>(_LRProperty_QNAME, LRProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISEventListExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extension", scope = EventListType.class)
    public JAXBElement<EPCISEventListExtensionType> createEventListTypeExtension(EPCISEventListExtensionType value) {
        return new JAXBElement<EPCISEventListExtensionType>(_EventListTypeExtension_QNAME, EPCISEventListExtensionType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ObjectEvent", scope = EventListType.class)
    public JAXBElement<ObjectEventType> createEventListTypeObjectEvent(ObjectEventType value) {
        return new JAXBElement<ObjectEventType>(_EventListTypeObjectEvent_QNAME, ObjectEventType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionEvent", scope = EventListType.class)
    public JAXBElement<TransactionEventType> createEventListTypeTransactionEvent(TransactionEventType value) {
        return new JAXBElement<TransactionEventType>(_EventListTypeTransactionEvent_QNAME, TransactionEventType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityEvent", scope = EventListType.class)
    public JAXBElement<QuantityEventType> createEventListTypeQuantityEvent(QuantityEventType value) {
        return new JAXBElement<QuantityEventType>(_EventListTypeQuantityEvent_QNAME, QuantityEventType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregationEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AggregationEvent", scope = EventListType.class)
    public JAXBElement<AggregationEventType> createEventListTypeAggregationEvent(AggregationEventType value) {
        return new JAXBElement<AggregationEventType>(_EventListTypeAggregationEvent_QNAME, AggregationEventType.class, EventListType.class, value);
    }

}
