
package org.ow2.aspirerfid.commons.ale.wsdl.ale;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 26 18:52:19 EET 2010
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "NoSuchSubscriberException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class NoSuchSubscriberExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100126185219L;
    
    private org.ow2.aspirerfid.commons.ale.wsdl.ale.NoSuchSubscriberException noSuchSubscriberException;

    public NoSuchSubscriberExceptionResponse() {
        super();
    }
    
    public NoSuchSubscriberExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchSubscriberExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSubscriberExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.ale.NoSuchSubscriberException noSuchSubscriberException) {
        super(message);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public NoSuchSubscriberExceptionResponse(String message, org.ow2.aspirerfid.commons.ale.wsdl.ale.NoSuchSubscriberException noSuchSubscriberException, Throwable cause) {
        super(message, cause);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public org.ow2.aspirerfid.commons.ale.wsdl.ale.NoSuchSubscriberException getFaultInfo() {
        return this.noSuchSubscriberException;
    }
}
